<?php

// Button Authorization by user name
// DO NOT change variable name only
// user name(s) in quotes ending with a semicolon
// Multiple login names per item can be defined
// EXAMPLE- $PERMUSER=array("admin1","admin2","joe","sam");
// Names must exactly match login names including case.
// YOU MUST HAVE THE SYNTAX CORRECT IN THIS FILE 
// OR SUPERMON WILL NOT RUN!!!
// NOTE - Items marked with (*) are considered
// a security risk to make public others at your discretion.
//
// Use the nano editor to mass change names in this file using
// the "control \" option. This will allow you to change the 
// below usernames to match real usernames you have created on
// your Supermon2 server. Then edit each button to add or change
// authorization for each user.
//
// Begin configuration area
//  
// Perm checkbox
$PERMUSER=array("admin","user1","user2","user3","user4");

// Connect button
$CONNECTUSER=array("admin","user1","user2","user3","user4");

// Disconnect button
$DISCUSER=array("admin","user1","user2","user3","user4");

// Monitor button
$MONUSER=array("admin","user1","user2","user3","user4");

// Local Monitor button
$LMONUSER=array("admin","user1","user2","user3","user4");

// DTMF button (*)
$DTMFUSER=array("admin","user1","user2","user3","user4");

// Asterisk lookup button
$ASTLKUSER=array("admin","user1","user2","user3","user4");

// RPT stats button
$RSTATUSER=array("admin","user1","user2","user3","user4");

// Bubble button
$BUBLUSER=array("admin","user1","user2","user3","user4");

// Favorites button
$FAVUSER=array("admin","user1","user2","user3","user4");

// Control Panel button (*)
$CTRLUSER=array("admin","user1","user2","user3","user4");

// Configuration Editor button (*)
$CFGEDUSER=array("admin","user1","user2","user3","user4");

// ASterisk Reload Button (*)
$ASTRELUSER=array("admin","user1","user2","user3","user4");

// Asterisk start button (*)
$ASTSTRUSER=array("admin","user1","user2","user3","user4");

// Asterisk stop button (*)
$ASTSTPUSER=array("admin","user1","user2","user3","user4");

// Asterisk restart button (*)
$FSTRESUSER=array("admin","user1","user2","user3","user4");

// Asterisk reboot button (*)
$RBTUSER=array("admin","user1","user2","user3","user4");

// Hamvoip update check button
$UPDUSER=array("admin","user1","user2","user3","user4");

// Hamvoip howto button
$HWTOUSER=array("admin","user1","user2","user3","user4");

// Allstar wiki button
$WIKIUSER=array("admin","user1","user2","user3","user4");

// CPU status button (*)
$CSTATUSER=array("admin","user1","user2","user3","user4");

// Allstar status button
$ASTATUSER=array("admin","user1","user2","user3","user4");

// Allstar node database button 
// Only active if using file node database
$EXNUSER=array("admin","user1","user2","user3","user4");

// Node info button
$NINFUSER=array("admin","user1","user2","user3","user4");

// Active node button
$ACTNUSER=array("admin","user1","user2","user3","user4");

// All nodes button
$ALLNUSER=array("admin","user1","user2","user3","user4");

// Database button (*)
// Note button only available if 
// setup in global.inc
$DBTUSER=array("admin","user1","user2","user3","user4");

// Supermon2 Log Display button
$SMLOGUSER=array("admin","user1","user2","user3","user4");

// GPIO button (*)
$GPIOUSER=array("admin","user1","user2","user3","user4");

// Linux Log button
$LLOGUSER=array("admin","user1","user2","user3","user4");

// Asterisk log button
$ASTLUSER=array("admin","user1","user2","user3","user4");

// Connection log button
$CLOGUSER=array("admin","user1","user2","user3","user4");

// IRLP LOG button
$IRLPLOGUSER=array("admin","user1","user2","user3","user4");

// Web access log button (*)
$WLOGUSER=array("admin","user1","user2","user3","user4");

// Web error log button (*)
$WERRUSER=array("admin","user1","user2","user3","user4");

// Restrict button (*)
$BANUSER=array("admin","user1","user2","user3","user4");

// simpleusb button
$SUSBUSER=array("admin","user1","user2","user3","user4");

// System Info button (*)
$SYSINFUSER=array("admin","user1","user2","user3","user4");

?>
